# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  SCHEDULER_PARAMETERS: "-J ArborX_CI -W 0:30 -nnodes 1 -P CSC333 -alloc_flags smt1"

stages:
  - buildDependencies
  - buildArborX
  - runBenchmarks
  - compare

BuildBoost:
  stage: buildDependencies
  script:
    - module load gcc/7.4.0 cuda/10.1.243 cmake/3.15.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
    - BOOST_VERSION=1.67.0 &&
      BOOST_VERSION_UNDERSCORE=$(echo "$BOOST_VERSION" | sed -e "s/\./_/g") &&
      BOOST_URL=https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source &&
      BOOST_ARCHIVE=boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2 &&
      wget --quiet ${BOOST_URL}/${BOOST_ARCHIVE} &&
      mkdir -p boost &&
      tar -xf ${BOOST_ARCHIVE} -C boost --strip-components=1 &&
      cd boost &&
      ./bootstrap.sh --prefix=${CI_PROJECT_DIR}/boost.install &&
      ./b2 -j8 hardcode-dll-paths=true dll-path=${CI_PROJECT_DIR}/boost.install link=static variant=release cxxflags=-w install
  tags:
    - nobatch
  artifacts:
    paths:
      - boost.install/

BuildBenchmark:
  stage: buildDependencies
  script:
    - module load gcc/7.4.0 cuda/10.1.243 cmake/3.15.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
    - git clone https://github.com/google/benchmark.git -b v1.4.1 &&
      cd benchmark &&
      git clone https://github.com/google/googletest.git -b release-1.8.1 &&
      mkdir build && cd build &&
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/benchmark.install .. &&
      make && make install
  tags:
    - nobatch
  artifacts:
    paths:
      - benchmark.install/

BuildKokkos:
  stage: buildDependencies
  script:
    - module load gcc/7.4.0 cuda/10.1.243 cmake/3.15.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
    - git clone --depth=1 --branch 3.1.00 https://github.com/kokkos/kokkos.git &&
      cd kokkos &&
      mkdir build &&
      cd build &&
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/kokkos.install -DCMAKE_CXX_COMPILER=${CI_PROJECT_DIR}/kokkos/bin/nvcc_wrapper -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ARCH_POWER9=ON -DKokkos_ARCH_VOLTA70=ON .. &&
      make &&
      make install
  tags:
    - nobatch
  artifacts:
    paths:
      - kokkos.install/

BuildArborXBranch:
  stage: buildArborX
  script:
    - module gcc/7.4.0 cuda/10.1.243 cmake/3.15.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
    - git merge origin/master
    - mkdir build && cd build &&
      cmake -DCMAKE_PREFIX_PATH="${CI_PROJECT_DIR}/kokkos.install;${CI_PROJECT_DIR}/benchmark.install;${CI_PROJECT_DIR}/boost.install" \
            -DCMAKE_CXX_COMPILER=${CI_PROJECT_DIR}/kokkos.install/bin/nvcc_wrapper \
            -DARBORX_ENABLE_MPI=ON \
            -DARBORX_ENABLE_TESTS=OFF \
            -DARBORX_ENABLE_BENCHMARKS=ON \
            -DARBORX_PERFORMANCE_TESTING .. &&
      make ArborX_BoundingVolumeHierarchy.exe
    - cp ./benchmarks/bvh_driver/ArborX_BoundingVolumeHierarchy.exe /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyBranch.exe
  tags:
    - nobatch

BuildArborXMaster:
  stage: buildArborX
  script:
    - module load gcc/7.4.0 cuda/10.1.243 cmake/3.15.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
    - git fetch
    - git worktree remove ${CI_PROJECT_DIR}/arborx-master
    - git worktree add ${CI_PROJECT_DIR}/arborx-master origin/master-ci 
    - cd ${CI_PROJECT_DIR}/arborx-master
    - mkdir build_master && cd build_master &&
      cmake -DCMAKE_PREFIX_PATH="${CI_PROJECT_DIR}/kokkos.install;${CI_PROJECT_DIR}/benchmark.install;${CI_PROJECT_DIR}/boost.install" \
            -DCMAKE_CXX_COMPILER=${CI_PROJECT_DIR}/kokkos.install/bin/nvcc_wrapper \
            -DARBORX_ENABLE_MPI=ON \
            -DARBORX_ENABLE_TESTS=OFF \
            -DARBORX_ENABLE_BENCHMARKS=ON \
            -DARBORX_PERFORMANCE_TESTING .. &&
      make ArborX_BoundingVolumeHierarchy.exe
    - cp ./benchmarks/bvh_driver/ArborX_BoundingVolumeHierarchy.exe /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyMaster.exe
  tags:
    - nobatch

RunBenchmarks:
  stage: runBenchmarks
  script:
    - export OMP_PROC_BIND=spread
    - export OMP_PLACES=threads
    - module load gcc/7.4.0 cuda/10.1.243 cmake/3.15.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
    - jsrun --smpiargs="-gpu" --nrs 1 --gpu_per_rs 6 --rs_per_host 1 --np 1 /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyBranch.exe --benchmark_format=json --no-header --benchmark_repetitions=10 | tee /ccsopen/proj/csc333/arborx-branch.json
    - jsrun --smpiargs="-gpu" --nrs 1 --gpu_per_rs 6 --rs_per_host 1 --np 1 /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyMaster.exe --benchmark_format=json --no-header --benchmark_repetitions=10 | tee /ccsopen/proj/csc333/arborx-master.json
  tags:
    - batch

CompareResults:
  stage: compare
  script:
    - module load python/3.6.6-anaconda3-5.3.0
    - /ccsopen/proj/csc333/tools/compare.py benchmarks /ccsopen/proj/csc333/arborx-master.json /ccsopen/proj/csc333/arborx-branch.json | grep "median\|mean"
  tags:
    - nobatch
