# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  SCHEDULER_PARAMETERS: "-J ArborX_CI -W 0:20 -nnodes 1 -P CSC333 -alloc_flags gpumps"

stages:
  - buildDependencies
  - buildArborX
  - buildArborXMaster
  - runBenchmarks
  - compare

BuildBoost:
  stage: buildDependencies
  before_script:
    - module load gcc/7.4.0
    - module load git
  script:
    - module load cmake
    - BOOST_VERSION=1.67.0 &&
      BOOST_VERSION_UNDERSCORE=$(echo "$BOOST_VERSION" | sed -e "s/\./_/g") &&
      BOOST_URL=https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source &&
      BOOST_ARCHIVE=boost_${BOOST_VERSION_UNDERSCORE}.tar.bz2 &&
      wget --quiet ${BOOST_URL}/${BOOST_ARCHIVE} &&
      wget --quiet ${BOOST_URL}/${BOOST_ARCHIVE}.asc &&
      wget --quiet ${BOOST_URL}/${BOOST_ARCHIVE}.json &&
      wget --quiet ${BOOST_URL}/${BOOST_ARCHIVE}.json.asc &&
      mkdir -p boost &&
      tar -xf ${BOOST_ARCHIVE} -C boost --strip-components=1 &&
      cd boost &&
      ./bootstrap.sh --prefix=${CI_PROJECT_DIR}/boost.install &&
      ./b2 -j8 hardcode-dll-paths=true dll-path=${CI_PROJECT_DIR}/boost.install link=static variant=release cxxflags=-w install
  tags:
    - nobatch
  artifacts:
    paths:
      - boost.install/

BuildBenchmark:
  stage: buildDependencies
  before_script:
    - module load gcc/7.4.0
    - module load git
  script:
    - module load cmake
    - git clone https://github.com/google/benchmark.git -b v1.4.1 &&
      cd benchmark &&
      git clone https://github.com/google/googletest.git -b release-1.8.1 &&
      mkdir build && cd build &&
      cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/benchmark.install .. &&
      make && make install
  tags:
    - nobatch
  artifacts:
    paths:
      - benchmark.install/

BuildKokkos:
  stage: buildDependencies
  before_script:
    - module load gcc/7.4.0
    - module load cuda  
    - module load git
  script:
    - module load cmake
    - git clone --depth=1 --branch 3.1.00 https://github.com/kokkos/kokkos.git &&
      cd kokkos &&
      mkdir build &&
      cd build &&
      cmake -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/kokkos.install -DCMAKE_CXX_COMPILER=${CI_PROJECT_DIR}/kokkos/bin/nvcc_wrapper -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ARCH_POWER9=ON -DKokkos_ARCH_VOLTA70=ON .. &&
      make &&
      make install
  tags:
    - nobatch
  artifacts:
    paths:
      - kokkos.install/

BuildArborX:
  stage: buildArborX
  before_script:
    - module load gcc/7.4.0
    - module load cuda
  script:
    - module load cmake
    - module load python
    - module load cuda
    - git branch
    - mkdir build && cd build &&
      cmake -DCMAKE_PREFIX_PATH="${CI_PROJECT_DIR}/kokkos.install;${CI_PROJECT_DIR}/benchmark.install;${CI_PROJECT_DIR}/boost.install" -DARBORX_ENABLE_MPI=ON -DARBORX_ENABLE_TESTS=OFF -DARBORX_ENABLE_BENCHMARKS=ON -DCMAKE_CXX_COMPILER=${CI_PROJECT_DIR}/kokkos.install/bin/nvcc_wrapper .. &&
      make VERBOSE=1 
    - export OMP_PROC_BIND=spread 
    - export OMP_PLACES=threads
    - cp ./benchmarks/bvh_driver/ArborX_BoundingVolumeHierarchyRegression.exe /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyRegressionBranch.exe
    - jsrun --smpiargs="-gpu" --nrs 1 --cpu_per_rs 42 --gpu_per_rs 6 --rs_per_host 1 --np 1 --latency_priority CPU-CPU --launch_distribution packed --bind packed:1 /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyRegressionBranch.exe --benchmark_format=json --no-header --benchmark_repetitions=30 | tee /ccsopen/proj/csc333/arborx-branch.json
    - cp /ccsopen/proj/csc333/arborx-branch.json .
  tags:
    - batch
  artifacts:
    paths:
      - build/arborx-branch.json

BuildArborXMaster:
  stage: buildArborX
  before_script:
    - module load gcc/7.4.0
    - module load cuda
  script:
    - module load cmake
    - module load python
    - module load git
    - module load cuda
    - ls
    - git branch
    - git fetch
    - git branch
    - git worktree remove ${CI_PROJECT_DIR}/arborx-master
    - git worktree add ${CI_PROJECT_DIR}/arborx-master origin/master-ci 
    - cd ${CI_PROJECT_DIR}/arborx-master
    - git log
    - mkdir build_master && cd build_master &&
      cmake -DCMAKE_PREFIX_PATH="${CI_PROJECT_DIR}/kokkos.install;${CI_PROJECT_DIR}/benchmark.install;${CI_PROJECT_DIR}/boost.install" -DARBORX_ENABLE_MPI=ON -DARBORX_ENABLE_TESTS=OFF -DARBORX_ENABLE_BENCHMARKS=ON -DCMAKE_CXX_COMPILER=${CI_PROJECT_DIR}/kokkos.install/bin/nvcc_wrapper .. &&
      make VERBOSE=1
    - export OMP_PROC_BIND=spread 
    - export OMP_PLACES=threads
    - cp ./benchmarks/bvh_driver/ArborX_BoundingVolumeHierarchyRegression.exe /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyRegressionMaster.exe
    - jsrun --smpiargs="-gpu" --nrs 1 --cpu_per_rs 42 --gpu_per_rs 6 --rs_per_host 1 --np 1 --latency_priority CPU-CPU --launch_distribution packed --bind packed:1 /ccsopen/proj/csc333/ArborX_BoundingVolumeHierarchyRegressionMaster.exe --benchmark_format=json --no-header --benchmark_repetitions=30 | tee /ccsopen/proj/csc333/arborx-master.json
    - cp /ccsopen/proj/csc333/arborx-master.json .
  tags:
    - batch
  artifacts:
    paths:
      - arborx-master/build_master/arborx-master.json

CompareResults:
  stage: compare
  before_script:
    - module load gcc/7.4.0
    - module load cuda
  script:
    - module load cmake
    - module load python
    - ls
    - benchmarks/tools/compare.py benchmarks arborx-master/build_master/arborx-master.json build/arborx-branch.json
  tags:
    - nobatch
