name: Mirror and run GitLab CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://code.ornl.gov/ecpcitest/alexa/"
      env:
        GITLAB_HOSTNAME: "code.ornl.gov"
        GITLAB_USERNAME: "6da"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "6927"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
